name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m unittest test.py
        
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: achengcalcreg.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t achengcalcreg.azurecr.io/health-calculator-app:${{ github.sha }} .
        docker push achengcalcreg.azurecr.io/health-calculator-app:${{ github.sha }}
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'health-calculator-webapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'achengcalcreg.azurecr.io/health-calculator-app:${{ github.sha }}'
